{% set name = "pytest-copie" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_copie-{{ version }}.tar.gz
  sha256: 2614cc0374f79890ea5b52f50f5c8fc3b896ac0c9aef5a3484809f67d5e478fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.14
    - copier
    - pytest

test:
  imports:
    - pytest_copie
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/12rambau/pytest-copie
  summary: The pytest plugin for your copier templates 📒
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 12rambau
