{% set name = "pytest-copie" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_copie-{{ version }}.tar.gz
  sha256: 4a95bb7d4ded6183bf9b1da8cce5b79ad3b4db1b1a8909d2ea6d87e491c76749

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - deprecated >=1.2.14
    - copier
    - pytest

test:
  imports:
    - pytest_copie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/12rambau/pytest-copie
  summary: The pytest plugin for your copier templates 📒
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 12rambau
